apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-vault
  namespace: modn-platform-configuration
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: vault-dev.awsweb.online
    http:
     paths:
     - path:
       backend:
          serviceName: vault
          servicePort: 8200

